#################################
## Hugo settings               ##
#################################

baseURL = "https://blog.jemu.name/"
DefaultContentLanguage = "en"
relativeURLs = false
languageCode = "en-us"
title = "Jemsu Blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
Paginate = 10

# Enable features
enableEmoji = true
enableGitInfo = true
# Rmarkdown special handling
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  show = "shows"
  package = "packages"

[markup]
  defaultMarkdownHandler = "goldmark" # "pandoc" or "goldmark" (default)
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
    [markup.tableOfContents]
      endLevel = 3
      ordered = false
      startLevel = 2

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

#################################
## Theme-specific settings     ##
#################################

[Params.matomo]
#  id = "12"
#  server = "analytics.tadaa-data.de/"
  id = "2"
  server = "matomo.jemu.name"

[Author]
  name = "jemus42"
  website = "https://jemu.name"
  email = "blog@jemu.name"
  github = "jemus42"
#  gitlab = "username"
  twitter = "jemus42"
#  reddit = "username"
#  linkedin = "username"
#  xing = "Lukas_Burk2"
  stackoverflow = "users/409362/jemus42"
#  instagram = "jemus42"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
  spotify = "jemus42"
  git-selfhosted = "git.tadaa-data.de/lukas"
  bandcamp = "jemus42"
#  paypal = "jemus42"
#  mastodon = "cybre.space/@jemus42"
