[[main]]
    name = "About"
    url = "about"
    identifier = "about"
    weight = 1

[[main]]
    name = "Projects"
    url = "projects"
    identifier = "projects"
    weight = 2

[[main]]
    name = "Posts"
    url = "post"
    identifier = "posts"
    weight = 3

# Submenu for post taxonomies
# [[main]]
#     name = "categories"
#     url = "categories"
#     parent = "posts"
#     weight = 1

[[main]]
    name = "Tags"
    url = "tags"
    parent = "posts"
    weight = 2

[[main]]
    name = "Shows"
    url = "shows"
    parent = "posts"
    weight = 3

[[main]]
    name = "R Packages"
    url = "packages"
    parent = "posts"
    weight = 4
# End submenu for taxonomies

#[[main]]
#    name = "Source"
#    url = "https://github.com/rbind/blog.jemu.name"
#    weight = "4"
