[build] 
  publish = "public"
  command = "hugo -D"
  HUGO_VERSION = "0.71.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_TITLE = "Development Preview - blog.jemu.name"

[context.branch-deploy.environment]
  HUGO_TITLE = "Branch Preview - blog.jemu.name"

[context.deploy-preview.environment]
  HUGO_TITLE = "Deploy Preview - blog.jemu.name"
